In [5]:
import torch
x=torch.arange(12,dtype=torch.float).reshape(4,3)
y=torch.ones(3,4)

In [6]:
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [7]:
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.mm(x,y)

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.],
        [21., 21., 21., 21.],
        [30., 30., 30., 30.]])

In [9]:
x@y

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.],
        [21., 21., 21., 21.],
        [30., 30., 30., 30.]])