In [1]:
import torch
x=torch.tensor([[0,1,2],[3,4,5]])

In [3]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [4]:
x.sum(axis=1)

tensor([ 3, 12])

In [5]:
(x.sum(axis=1)).shape

torch.Size([2])

In [6]:
x=x.sum(axis=1,keepdims=True)

In [7]:
x

tensor([[ 3],
        [12]])

In [8]:
x.shape

torch.Size([2, 1])

In [9]:
y=torch.tensor([[0,1,2],[3,4,5]])

In [10]:
y=y.sum(axis=0,keepdims=True)

In [11]:
y

tensor([[3, 5, 7]])

In [13]:
y.shape

torch.Size([1, 3])

In [15]:
y=torch.tensor([[0,1,2],[3,4,5]])

In [16]:
y.cumsum(axis=0)

tensor([[0, 1, 2],
        [3, 5, 7]])