In [5]:
import torch
x=torch.arange(12,dtype=torch.float32)
x,x.sum()

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor(66.))

In [7]:
x.shape

torch.Size([12])

In [8]:
x=x.reshape(3,4)

In [9]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
x.sum(axis=0),(x.sum(axis=0)).shape



(tensor([12., 15., 18., 21.]), torch.Size([4]))

In [12]:
x.sum(axis=1)

tensor([ 6., 22., 38.])

In [17]:
x.sum(axis=[0,1])==x.sum()

tensor(True)

In [18]:
x.mean()

tensor(5.5000)

In [19]:
x.mean()==x.sum()/x.numel()

tensor(True)

In [20]:
x.mean(axis=0)

tensor([4., 5., 6., 7.])

In [ ]:
x.mean(axis=0)==x.sum(axis=0)/x.