In [1]:
import torch
x=torch.arange(10,dtype=torch.float32)
print(x)
x.numel()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


10

In [2]:
x.size()

torch.Size([10])

In [3]:
x.reshape(5,2)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [4]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
x.reshape(5,2)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [6]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
x=torch.arange(16,dtype=torch.int32)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int32)

In [10]:
torch.randn(2,3,4)

tensor([[[-0.2101,  0.8066,  1.6769, -0.8964],
         [-1.1878,  0.2881,  0.5061, -0.7977],
         [-1.6464,  0.1404, -0.3107, -1.5505]],

        [[ 0.8960,  0.1798, -0.2791,  0.1831],
         [-0.0943, -0.3697, -0.3866, -2.0629],
         [-0.9622, -0.2891,  0.7605,  0.5644]]])

In [11]:
torch.tensor([[2,3,4],[2,3,4]])

tensor([[2, 3, 4],
        [2, 3, 4]])

In [12]:
torch.tensor([[2,3,4],[4,3,3]])

tensor([[2, 3, 4],
        [4, 3, 3]])

In [13]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int32)

In [14]:
x[-1]

tensor(15, dtype=torch.int32)

In [15]:
x[0:10]


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [16]:
x[0:5]

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [17]:
x[-1],x[1:3]

(tensor(15, dtype=torch.int32), tensor([1, 2], dtype=torch.int32))

In [18]:

x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int32)

In [19]:
x[1:2]=11

In [20]:
x

tensor([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int32)

In [21]:
y=torch.tensor([[2,3,4],[5,6,7],[1,2,3]])
y

tensor([[2, 3, 4],
        [5, 6, 7],
        [1, 2, 3]])

In [22]:
y[1]

tensor([5, 6, 7])

In [23]:
y[0,1]

tensor(3)

In [24]:
y[0:1]

tensor([[2, 3, 4]])

In [25]:
y[0:1]=2

In [26]:
y[0:1]

tensor([[2, 2, 2]])

In [27]:
y

tensor([[2, 2, 2],
        [5, 6, 7],
        [1, 2, 3]])

In [28]:
y[0:3]

tensor([[2, 2, 2],
        [5, 6, 7],
        [1, 2, 3]])

## y[0:2

In [29]:
y

tensor([[2, 2, 2],
        [5, 6, 7],
        [1, 2, 3]])

In [30]:
y[:2,:]=12

In [31]:
y

tensor([[12, 12, 12],
        [12, 12, 12],
        [ 1,  2,  3]])

In [32]:
a=torch.tensor([[1,2,3],[4,5,6]])

In [33]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
torch.exp(a)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [35]:
x=torch.tensor([1,2,3,4])
print(x)

tensor([1, 2, 3, 4])


In [36]:
y=torch.tensor([5,6,7,8])
print(y)

tensor([5, 6, 7, 8])


In [37]:
x+y

tensor([ 6,  8, 10, 12])

In [38]:
x*y


tensor([ 5, 12, 21, 32])

In [39]:
y=torch.tensor([2,3,4,5,6])

In [40]:
y

tensor([2, 3, 4, 5, 6])

In [41]:
x+y

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [43]:
y=torch.tensor([5,6,7,8])
print(y)

tensor([5, 6, 7, 8])


In [44]:
x+y

tensor([ 6,  8, 10, 12])

In [46]:
x/y

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [47]:
x=torch.arange(12,dtype=torch.float32)

In [48]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [49]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
y=torch.arange(12,dtype=torch.float32)

In [51]:
y

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [52]:
y.reshape(2,6)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [53]:
torch.cat((x,y),dim=0)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  0.,  1.,
         2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [54]:
x==y

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [58]:
x=x.reshape(1,12)

In [59]:
y=y.reshape(12,1)

In [60]:
x==y

tensor([[ True, False, False, False, False, False, False, False, False, False,
         False, False],
        [False,  True, False, False, False, False, False, False, False, False,
         False, False],
        [False, False,  True, False, False, False, False, False, False, False,
         False, False],
        [False, False, False,  True, False, False, False, False, False, False,
         False, False],
        [False, False, False, False,  True, False, False, False, False, False,
         False, False],
        [False, False, False, False, False,  True, False, False, False, False,
         False, False],
        [False, False, False, False, False, False,  True, False, False, False,
         False, False],
        [False, False, False, False, False, False, False,  True, False, False,
         False, False],
        [False, False, False, False, False, False, False, False,  True, False,
         False, False],
        [False, False, False, False, False, False, False, False, False,  

In [70]:
x=torch.tensor([0,1,2,3,4,5])

In [71]:
x

tensor([0, 1, 2, 3, 4, 5])

In [77]:
y=torch.tensor([0,1,3,9,2,5])
y

tensor([0, 1, 3, 9, 2, 5])

In [78]:
y=y.reshape(6,1)

In [79]:
y

tensor([[0],
        [1],
        [3],
        [9],
        [2],
        [5]])

In [80]:
x==y


tensor([[ True, False, False, False, False, False],
        [False,  True, False, False, False, False],
        [False, False, False,  True, False, False],
        [False, False, False, False, False, False],
        [False, False,  True, False, False, False],
        [False, False, False, False, False,  True]])

In [81]:
 x.sum()

tensor(15)