In [1]:
import torch

In [2]:
x=torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [3]:
y=x.numpy()

In [4]:
y

array([1, 2, 3])

In [7]:
a=torch.from_numpy(y)

In [8]:
a

tensor([1, 2, 3])

In [9]:
type(y)

numpy.ndarray

In [10]:
type(a)

torch.Tensor

In [11]:
y[0]=100

In [12]:
x

tensor([100,   2,   3])

In [13]:
x[1]=50

In [14]:
y

array([100,  50,   3])

In [15]:
x.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [16]:
float(x)

ValueError: only one element tensors can be converted to Python scalars

In [17]:
int(x)

ValueError: only one element tensors can be converted to Python scalars

In [18]:
z=torch.tensor([3.6])

In [19]:
z.item()

3.5999999046325684

In [20]:
float(z)

3.5999999046325684

In [21]:
int(z)

3