In [1]:
import torch

In [9]:
x=torch.arange(6,dtype=torch.float32).reshape(2,3)

In [10]:
x

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [11]:
y=x.clone()

In [12]:
y

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [13]:
x+y

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [17]:
x*y #   hadamard product

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [22]:
a=2
a+x,a*x

(tensor([[2., 3., 4.],
         [5., 6., 7.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))