In [4]:
import torch
x=torch.tensor([1,2,3])

In [5]:
x

tensor([1, 2, 3])

In [8]:
print(x)

tensor([1, 2, 3])


In [16]:
y=torch.tensor([4,5,6])

In [17]:
y

tensor([4, 5, 6])

In [18]:
before=id(y)

In [19]:
y=y+x

In [20]:
after=id(y)

In [21]:
before==after

False

In [22]:
y=torch.tensor([4,5,6])

In [23]:
y

tensor([4, 5, 6])

In [24]:
before=id(y)

In [25]:
y[:]=x+y

In [26]:
after=id(y)

In [27]:
before==after


True

In [28]:
z=torch.zeros(12)

In [29]:
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
z=torch.zeros_like(y)

In [33]:
x

tensor([1, 2, 3])

In [34]:
z

tensor([0, 0, 0])

In [35]:
before=id(x)

In [36]:
x+=y

In [37]:
after=id(x)

In [38]:
before==after

True