In [1]:
import torch

In [2]:
x=torch.arange(6)

In [3]:
x

tensor([0, 1, 2, 3, 4, 5])

In [4]:
x=x.reshape(3,2)

In [5]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
x.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [7]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [11]:
x=torch.arange(9)

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
x=x.reshape(3,3)

In [15]:
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
x==x.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [17]:
y=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [18]:
y==y.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])